### ISSUE TITLE
Leverage a custom application instead of bookinfo

### ISSUE THREAD

**Issue by cmluciano** [IBM/istio-intro#7]
We should try to rewrite or modify https://github.com/estesp/flightassist to work with these demos. The flightassist example can be tuned to make failures more obvious and we can also demonstrate more features like Egress policy.

**Comment by MHBauer** [comment]
Anything but bookinfo.

Bad names.

**Comment by MHBauer** [comment]
ratings should be called "book-stars" or something.

Edit: Now I'm thinking about "The Land Before Time".
